name: Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: apb-proteobench
    steps:
      - name: Check out APB ProteoBench
        uses: actions/checkout@v6
        with:
          path: apb-proteobench

      - name: Check out compatible APB2
        uses: actions/checkout@v6
        with:
          repository: anndata-omics-bridge/apb2
          ref: f6131af4b71562546b19af389060930ca4eec32c
          path: apb2

      - name: Check out compatible APB Catalog
        uses: actions/checkout@v6
        with:
          repository: anndata-omics-bridge/apb-catalog
          ref: c5e344c81522cd867523ef343e4d75d76019665e
          path: apb-catalog

      - name: Check out compatible APB FASTA
        uses: actions/checkout@v6
        with:
          repository: anndata-omics-bridge/apb-fasta
          ref: f8940777cca33aacc9370530927d6b7d735f03c3
          path: apb-fasta

      - name: Check out compatible protein-fasta
        uses: actions/checkout@v6
        with:
          repository: anndata-omics-bridge/protein-fasta
          ref: 069af7a883c43caa56349e81f692527b4af16356
          path: protein_fasta

      - name: Check out compatible Prozor
        uses: actions/checkout@v6
        with:
          repository: anndata-omics-bridge/prozor
          ref: d11f3a6ddd5632bb5092a96733aa7c9e007a579c
          path: prozor

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.9.8"
          enable-cache: true

      - name: Build documentation
        run: uv run --frozen --group docs zensical build --clean --strict

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: apb-proteobench/public

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
